# Generated by Django 4.1.2 on 2022-10-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='profile/%Y'),
        ),
    ]
