# Generated by Django 4.1.2 on 2022-10-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, choices=[('action', 'action'), ('comedy', 'comedy'), ('drama', 'drama'), ('horror', 'horror'), ('romance', 'romance'), ('thriller', 'thriller'), ('sports', 'sports'), ('adventure', 'sports')], max_length=30, null=True)),
                ('poster', models.ImageField(upload_to='media/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
