# Generated by Django 4.1.2 on 2022-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieposter',
            name='film_industry',
            field=models.CharField(blank=True, choices=[('bollywood', 'Bollywood'), ('hollywood', 'Hollywood'), ('tollywood', 'Tollywood'), ('webseries', 'Webseries')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('sports', 'Sports'), ('adventure', 'Adventure')], max_length=30, null=True),
        ),
    ]
