# Generated by Django 4.1.2 on 2022-10-12 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_movieposter_film_industry_alter_movieposter_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieposter',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
