# Generated by Django 4.1.2 on 2022-10-12 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_movieposter_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieposter',
            old_name='poster',
            new_name='poster_image',
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
