# Generated by Django 4.1.2 on 2022-10-12 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_movieposter_author_alter_movieposter_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieposter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='member',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
