# Generated by Django 4.1.2 on 2022-10-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_movieposter_options_alter_movieposter_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieposter',
            name='film_industry',
            field=models.CharField(blank=True, choices=[('Bollywood', 'Bollywood'), ('Hollywood', 'Hollywood'), ('Tollywood', 'Tollywood'), ('Webseries', 'Webseries')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movieposter',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Sports', 'Sports'), ('Adventure', 'Adventure')], max_length=30, null=True),
        ),
    ]
